# This workflow will install Python dependencies, run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  bench-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          ref: ${{ github.ref || 'refs/heads/main' }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9    
    - name: Benchmark
      run: |
        pip install pytest pytest-benchmark
        python -m pytest test_all.py --benchmark-json output.json
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
          tool: 'pytest'
          output-file-path: output.json
    - name: Push benchmark result
      run: git push 'https://steelannelida:${{ secrets.GITHUB_TOKEN }}@github.com/steelannelida/benchmarktest.git' gh-pages:gh-pages